Fix docker build
dnanexus/dxda pull request #76
Opened 2023-02-27 10:02 UTC by wormsik

- update base image to Ubuntu 22.04
- update Go version to 1.16.6 (as per releases)
- fix build error by using `install` instead of `get` (closes #70)

2023-02-27 13:52 UTC, kpjensen approved these changes

2023-02-28 14:30 UTC, kpjensen requested changes

2023-02-28 14:30 UTC, kpjensen commented on Dockerfile
>  RUN mkdir -p /builds/dx-download-agent-osx /builds/dx-download-agent-linux && \
Can this section be removed?

2023-03-01 07:32 UTC, wormsik commented on Dockerfile
>  RUN mkdir -p /builds/dx-download-agent-osx /builds/dx-download-agent-linux && \
done

2023-03-01 13:47 UTC, kpjensen approved these changes

2023-03-01 13:48 UTC, merged